### ISSUE TITLE
Mesh name override is not working

### ISSUE THREAD

**Issue by jasonrichardsmith** [aws/aws-app-mesh-inject#39]
When attempting this annotation it does not seem that the mesh name override is working correctly.

https://github.com/jasonrichardsmith/aws-app-mesh-examples/blob/interactive-demo/examples/demo/demo/colors.yaml#L43-L44

deployed pod looks like this
```yaml
# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: v1
kind: Pod
metadata:
  annotations:
    appmesh.k8s.aws/mesh: appmesh-demo
  creationTimestamp: "2019-04-08T12:04:04Z"
...
  - env:
    - name: APPMESH_VIRTUAL_NODE_NAME
      value: mesh/testmesh/virtualNode/blue-appmesh-demo
```
