### ISSUE TITLE
StatsD / DogStatsD support

### ISSUE THREAD

**Issue by PaulMaddox** [aws/aws-app-mesh-inject#48]
The standard metrics exposed by the Envoy Prometheus endpoint do not include latency information. This is a shame, as it's tough to build great Grafana dashboards without it.

To solve this, we should do two things:

1. We should allow the injector to control whether the Envoy proxy emits statsd metrics (via [ENABLE_ENVOY_DOG_STATSD](https://docs.aws.amazon.com/app-mesh/latest/userguide/envoy.html)). This will allow customers to export metrics to any statsd/dogstatsd reciever (either datadog something like [statsd_exporter](https://github.com/prometheus/statsd_exporter)).

2. We should allow optional injection of a [statsd_exporter](https://github.com/prometheus/statsd_exporter) sidecar container (which collects metrics, and provides an endpoint prometheus can scrape).

I have a PR i'm creating for this (all working, just want to add a few more tests before submitting). It adds two new configuration environment variables:

> (Optional) If enabled, Envoy will emit DogStatsD metrics to 127.0.0.1:8125, where it expects to find a statsd receiver. This could be either a Datadog sidecar, or something like [statsd_exporter](https://github.com/prometheus/statsd_exporter) (see below). 
```
$ export ENABLE_STATSD=true
```

> (Optional) To deploy [statsd_exporter](https://github.com/prometheus/statsd_exporter) as a sidecar, which can recieve statsd metrics and republish them in Prometheus format. It listens for metrics on 127.0.0.1:8125, and exposes a prometheus endpoint at 127.0.0.1:9201. This is useful as statsd provides metrics around request latency (p50, p99 etc), whereas the standard Envoy prometheus endpoint does not. 
```
$ export INJECT_STATSD_EXPORTER_SIDECAR=true
```

**Comment by PaulMaddox** [comment]
Example Prometheus configuration for scraping both the Envoy prometheus endpoint, and also the new statsd_exporter one:

```
    # Scrape config for AppMesh statsd sidecar
    - job_name: 'appmesh-statsd-v1'
      metrics_path: /metrics
      kubernetes_sd_configs:
      - role: pod
      relabel_configs:
      - source_labels: [__meta_kubernetes_pod_container_name]
        action: keep
        regex: '^envoy$'
      - source_labels: [__address__]
        action: replace
        regex: (.*):(9901)
        replacement: ${1}:9102
        target_label: __address__
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
      - source_labels: [__meta_kubernetes_namespace]
        action: replace
        target_label: kubernetes_namespace
      - source_labels: [__meta_kubernetes_pod_name]
        action: replace
        target_label: kubernetes_pod_name

    # Scrape config for AppMesh Envoy sidecar
    - job_name: 'appmesh-envoy'
      metrics_path: /stats/prometheus
      kubernetes_sd_configs:
      - role: pod
      relabel_configs:
      - source_labels: [__meta_kubernetes_pod_container_name]
        action: keep
        regex: '^envoy$'
      - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
        action: replace
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: ${1}:9901
        target_label: __address__
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
      - source_labels: [__meta_kubernetes_namespace]
        action: replace
        target_label: kubernetes_namespace
      - source_labels: [__meta_kubernetes_pod_name]
        action: replace
        target_label: kubernetes_pod_name
```
